### ISSUE TITLE
Comment：Table I, the MAE of Halfmile is 3.8±4.3？

### ISSUE THREAD

**Issue by newbee-ML** [mila-iqia/hardpicks#2]
Page4, in Table I, why the MAE of Halfmile is 3.8±4.3? That means the min of MAE is 3.8-4.3=-1.5, which is an invalid value for MAE. There is the same issue with MBE of Halfmile.

**Comment by plstcharles** [comment]
Hello,

The +/- values listed in the table next to the scores are standard deviations, meaning it is possible to have a bigger std than the mean without going below zero; see the example below:
```
    import numpy as np
    x = np.maximum((np.random.randn((10000)) * 1000) + 200, 0)  # x only contains 10,000 non-negative values
       # x = array([   0.        ,    0.        , 1202.40842765, ...,  166.87168064, 1419.92815718,    0.        ])
    x.mean()
        # 506.12034556992194
    x.std()
        # 647.2860713596114
```

For the MBE, the scores can actually be negative; it's like a MAE score where we did not apply an absolute value function.

Let me know if this clear things up!

**Comment by newbee-ML** [comment]
Thanks for your answer and the datasets built by your team. There is no problem with your answer, and I believe your open-source datasets are valuable for the first break auto-picking problem.
